feature/aytochiloeches-36-access-to-participants-database
aspgems/consul pull request #1
Opened 2017-04-21 09:36 UTC by reperezz

Close [#TG-ISSUE-36](https://tree.taiga.io/project/ailopez-chiloeches-decide/issue/36)

2017-04-21 09:44 UTC, zjuanma commented on config/application_custom.rb
> +require 'csv'
Este require no seria mejor ponerlo donde se usa lo del csv, en custom/user.rb?

2017-04-21 09:47 UTC, reperezz commented on config/application_custom.rb
> +require 'csv'
Sí, se puede añadir solo en el modelo User, pero estando en ese punto está accesible CSV en cualquier sitio de la aplicación.

2017-04-21 10:18 UTC, ace requested changes

2017-04-21 10:18 UTC, ace commented on app/controllers/custom/admin/participants_controller.rb
> +    @users = User.all.order('created_at desc')
El `order` debería ir en un scope del modelo, el controlador no necesita saber que la columna concreta se llama `created_at`.
El `all` es redundante, se está montando un objeto `relation` al que luego en el método `to_csv` se le va a volver a hacer un `all`.
Dado que no se hace nada con el objeto más allá de la acción, no es necesario que sea una variable de instancia, basta con `users`.

2017-04-21 10:18 UTC, ace commented on app/models/custom/user.rb
> +    CSV.generate(headers: true) do |csv|
¿Es necesario el `headers: true`? Estamos escribiendo el fichero, así que lo que le mandemos es lo que escribe, diría que esa opción solo tiene sentido en lectura.

2017-04-21 10:18 UTC, ace commented on app/views/custom/admin/_menu.html.erb
> +    <li <%= "class=active" if controller_name == "tags" %>>
Esta misma construcción para asignar la clase css en 17 líneas pide a gritos un helper.

2017-04-21 10:18 UTC, ace commented on config/application_custom.rb
> +require 'csv'
+1 al comentario de @zjuanma, si en el futuro hace falta en más sitios, ya se verá.

2017-04-21 10:21 UTC, reperezz commented on app/models/custom/user.rb
> +    CSV.generate(headers: true) do |csv|
Ese fichero es para comprobación por parte del cliente. El cliente lo va a leer y las cabeceras informan de lo que contiene cada columna. Es necesario.

2017-04-21 10:28 UTC, reperezz commented on app/views/custom/admin/_menu.html.erb
> +    <li <%= "class=active" if controller_name == "tags" %>>
Si te fijas es un partial dentro de la carpeta custom que en el caso de Consul es una copia del partial definido en la rama principal de Consul. Podemos intentar seguir el modelo establecido por Consul o definir el nuestro propio, pero eso supondrá más dificultad a la hora hacer merges con nuevos contenidos en la rama master de Consul o esperas por nuestros PR a la línea oficial de Consul. En este proyecto habría que tener claro ese tema.

2017-04-21 10:40 UTC, reperezz commented on app/controllers/custom/admin/participants_controller.rb
> +    @users = User.all.order('created_at desc')
Ok

2017-04-21 14:07 UTC, zjuanma commented on app/views/custom/admin/_menu.html.erb
> +    <li <%= "class=active" if controller_name == "tags" %>>
no estoy deacuerdo con tigo @reperezz, desde el momento que haces un custom, eso ya no lo vas a volver a mezclar con master, así que puedes definir el helper como ha dicho @ace

2017-04-21 14:10 UTC, reperezz commented on app/views/custom/admin/_menu.html.erb
> +    <li <%= "class=active" if controller_name == "tags" %>>
Si hay cambios en el fichero que has customizado en la parte de master no añades esos cambios a tu fichero customizado? Entonces si hay nuevas entradas en ese menú de administración tú no las metes?

2017-04-21 14:23 UTC, shernade commented on app/views/custom/admin/verifications/index.html.erb
> +      <td><%= I18n.l(user.date_of_birth.to_datetime.to_date) if user.date_of_birth %></td>
el .to_datetime.to_date es necesario?

2017-04-21 14:25 UTC, ace commented on app/models/custom/user.rb
> +    CSV.generate(headers: true) do |csv|
¿Y eso que tiene que ver? Un .csv es un fichero de texto plano. Cuando lo lea la primera línea la interpretará como cabeceras y esa línea es la que metes con los `attributes`. Una cosa es que sean necesarias las cabeceras, otra que lo sea esa opción, que no debe hacer nada en escritura.

2017-04-21 14:31 UTC, ace commented on app/views/custom/admin/verifications/index.html.erb
> +      <td><%= I18n.l(user.date_of_birth.to_datetime.to_date) if user.date_of_birth %></td>
Yo no le veo ningún sentido, `date_of_birth` (empezamos bien con el nombre) es un `datetime` (toma moreno) en bbdd, así que el `.to_datetime` parece que no hace ninguna falta. (Y ya se que todo lo anterior no es cosa nuestra, que venía así, pero si no lo digo reviento :D)

2017-04-21 14:40 UTC, ace commented on app/views/custom/admin/_menu.html.erb
> +    <li <%= "class=active" if controller_name == "tags" %>>
Sí, pero como es otro fichero y se van a tener que meter a mano, será el momento perfecto para adaptar esas nuevas entradas al helper.

2017-04-21 15:02 UTC, reperezz commented on app/views/custom/admin/verifications/index.html.erb
> +      <td><%= I18n.l(user.date_of_birth.to_datetime.to_date) if user.date_of_birth %></td>
Yo solo le he añadido el if al final porque si no tenía valor en el campo date_of_birth daba error. Pero es cierto que al ser un datetime no es necesario el .to_datetime. El .to_date si para mostrar solo la fecha en formato dd/mm/YYYY

2017-04-21 15:03 UTC, reperezz commented on app/views/custom/admin/_menu.html.erb
> +    <li <%= "class=active" if controller_name == "tags" %>>
Ok, añado un helper

2017-04-21 15:06 UTC, reperezz commented on app/models/custom/user.rb
> +    CSV.generate(headers: true) do |csv|
Ok, ya te comprendí. Cierto, ese parámetro solo vale en caso de lectura del csv. Lo elimino.

2017-04-21 15:26 UTC, eLafo commented on app/views/custom/admin/verifications/index.html.erb
> +      <td><%= I18n.l(user.date_of_birth.to_datetime.to_date) if user.date_of_birth %></td>
Pues si el to_datetime no es necesario, quitémoslo...

2017-04-21 15:48 UTC, ace commented on app/views/custom/admin/verifications/index.html.erb
> +      <td><%= I18n.l(user.date_of_birth.to_datetime.to_date) if user.date_of_birth %></td>
Como nota al margen, siendo estrictos el `to_date` tampoco haría falta, si solo se quiere la fecha, bastaría con pasarle al `I18n.l` el formato que se quiere.

2017-04-21 15:51 UTC, eLafo requested changes
Efectivamente hay que quitar la opción headers del csv y extraer el código que decide si se añade la clase "active" a un helper

2017-04-21 16:15 UTC, ace commented on app/views/custom/admin/_menu.html.erb
> +    <li <%= "class=active" if controller_name == "tags" %>>
Mirándolo con un poco más de atención, casi te diría que el helper puede montar no solo eso, sino toda la entrada de menú. Son todas idénticas salvo cuatro cosas, el nombre de controlador para la clase active, el path, el icono y el elemento de I18n. Con esos cuatro parámetros se pueden montar todos los elementos de menú en un solo método y cada uno te queda de una línea (salvo los que tienen un if condicionando).

2017-04-24 09:01 UTC, ace commented on app/helpers/tags_helper.rb
> +  def nav_element(match_controller, path = root_path, legend = '', options = {}, &block)
Me sobra un poco el baile con las `options` :tag_name y :class_icon. Una nunca se pasa y siempre vale el valor por defecto y la otra siempre se pasa y el valor por defecto no pinta nada. Y sobre todo el bloque, no tenemos ese uso por ningún lado.

2017-04-24 09:59 UTC, eLafo commented on config/application_custom.rb
> +require 'csv'
+1

2017-04-24 10:06 UTC, eLafo commented on app/helpers/tags_helper.rb
> +  def nav_element(match_controller, path = root_path, legend = '', options = {}, &block)
Yo creo que tiene sentido hacer configurable tanto el tag como el class icon. Otra cosa es que ahora mismo no lo utilicemos como cliente y que hayamos pecado un pelín de sobrearquitectura, pero a mí personalmente me cuadra.

2017-04-24 10:22 UTC, ace commented on app/helpers/tags_helper.rb
> +  def nav_element(match_controller, path = root_path, legend = '', options = {}, &block)
El tag no lo veo, toda esa navegación va en un `ul`, si no va a ser un `li` el cambio va a ser más grande que el helper, pero bueno, tampoco tiene más importancia. Del class icon lo que comento es que siempre se está recibiendo, no le veo sentido al || con un valor por defecto (que además me parece arbitrario, ni siquiera es el icono más usado). Lo del bloque sí que ya me parece demasiado sobrearquitecturado.

2017-04-24 11:36 UTC, eLafo commented on app/helpers/tags_helper.rb
> +  def nav_element(match_controller, path = root_path, legend = '', options = {}, &block)
Bueno, supongo que es un tema de dónde poner la línea. A mí este helper se me parece bastante  los que te da rails, con opciones para configurar diferentes cosas. Por eso a mí no me canta tanto. Me parece que aunque sea una solución relativamente grande para un caso puntual, se compensa siguiendo cosas que hace rails y por lo tanto respetando el principio de la mínima sorpresa.

Dicho esto a mí ambas opciones me parecen válidas con sus pros y sus contras. Puesto que las consecuencias de la decisión no me las como yo, sino que os las coméis los que estáis en el día a día del proyecto, lo suyo es que llegués a un consenso ;-)

2017-04-25 07:54 UTC, reperezz commented on app/helpers/tags_helper.rb
> +  def nav_element(match_controller, path = root_path, legend = '', options = {}, &block)
Yo ya no perdería más tiempo con esto. Esas opciones que a Andrés le parecen sobrearquitecturación, palabra sobrecargada en sí misma, dan flexibilidad al método y que pueda usarse el día de mañana en una pestañas o con un contenido diferente, sin que suponga una difícil comprensión de lo que ahí se está haciendo o de rendimiento.

2017-04-25 08:21 UTC, ace commented on app/helpers/tags_helper.rb
> +  def nav_element(match_controller, path = root_path, legend = '', options = {}, &block)
Hombre, algo más complicado lo ha hecho. Como no hay teses te has ahorrado esa parte, pero esta flexibilidad llevaría asociados varios teses adicionales. Que un helper de rails te de esta flexibilidad me parece bien, el framework te ofrece posibilidades para usarlo como quieras/necesites. En este caso, teníamos todos los usos antes del helper, añadir 'futuribles' entra en esa línea de la optimización prematura que quizá no se use nunca.
En cualquier caso, tienes razón, ya le hemos dedicado bastante tiempo, por mi adelante.

2017-04-25 08:21 UTC, ace approved these changes

2017-04-25 08:34 UTC, eLafo commented on app/helpers/tags_helper.rb
> +  def nav_element(match_controller, path = root_path, legend = '', options = {}, &block)
+1 a lo de los tests que comenta @ace

2017-04-25 08:47 UTC, eLafo commented
Rubocop se queja en varios de los archivos modificados. Antes de mergear, hay que arreglar esas ofensas, o al menos justificarlas

2017-04-25 08:49 UTC, eLafo requested changes
Rubocop se queja en los siguientes archivos:

- app/controllers/custom/admin/participants_controller.rb
- app/models/custom/user.rb
- app/views/custom/admin/_menu.html.erb
- app/views/custom/admin/verifications/index.html.erb
- config/locales/custom/admin.es.yml
- config/routes.rb

Antes de mergear, hay que corregir esas ofensas, o al menos justificarlas

2017-04-25 15:46 UTC, eLafo approved these changes

2017-04-25 17:24 UTC, merged