Added Cancel verification button in pending verification admin view
aspgems/consul pull request #4
Opened 2017-05-02 11:44 UTC by Miguelkode

This is related to : https://tree.taiga.io/project/ailopez-chiloeches-decide/issue/40https://tree.taiga.io/project/ailopez-chiloeches-decide/issue/40

Here, we add a "cancel verification" button in the "admin pending verifications view" to Cancel this verification.

2017-05-02 14:16 UTC, ace requested changes
Tocho va. :-)
Aparte de los detalles comentados, algunos de los cuales tengo claro que vienen heredados por copiar el método create (no se podría arreglar?), no me acaba de gustar como está montado todo esto.
Tenemos un controlador supuestamente de verificaciones, pero que en realidad maneja dos recursos diferentes, según la acción.
Tanto index como search (y el nuevo destroy) manejan un recurso 'verificación pendiente' o 'usuario no verificado'. El create, sin embargo, crea una 'verificación' (sin pendiente). A mí eso me suena a otro controlador (si me apuras a una acción verificar/validar aquí mismo).
Esto nos lleva al problema con la ruta. Supongo que por mantener la estructura del create (con un parámetro user_id), se han acabado definiendo dos rutas, la normal y una asociada a la colección.
La que se está usando es la segunda, porque no se está pasando ningún parámetro id para poder usar la primera.
La que molaría es la primera, es un destroy sobre un recurso, simplemente usando el user_id como parámetro id. Nos sirve perfectamente como identificador. 
Lo que me chirría en ese caso es que estaríamos usando user_id de forma distinta en el create y el destroy en el mismo controlador y lo hace un poco lioso. En el fondo el create es el que me sobra aquí, vaya.

2017-05-02 14:16 UTC, ace commented on app/models/custom/user.rb
> +  def self.destroy_verification(user)
Un método de clase que recibe una instancia como parámetro y que llama a métodos de la instancia... esto ha de ser un método de instancia.

2017-05-02 14:16 UTC, ace commented on app/controllers/custom/admin/verifications_controller.rb
> +    User.destroy_verification(@user) if @user
Para qué es necesario el condicional? `@user` se obtiene con un `find` por `id`, así que si no existe va a saltar una excepción y no va a seguir la ejecución.
Por otro lado, lo que pongo en el modelo, método de clase recibiendo una instancia suya por parámetro -> método de instancia

2017-05-02 14:16 UTC, ace commented on app/controllers/custom/admin/verifications_controller.rb
> +    redirect_to search_admin_verifications_path(request.query_parameters.dup.extract!(:term, :page)),
Por qué se hace un `dup` y un `extract!` (copiar el objeto parámetros y extraer borrando esas dos claves) cuando se puede simplemente 'consultar' las claves sin borrarlas en el objeto inicial con un simple `slice` ?

2017-05-02 14:16 UTC, ace commented on app/controllers/custom/admin/verifications_controller.rb
> +                notice: t("admin.settings.flash.updated")
Nit: No se si habéis configurado rubocop en otro sentido, pero texto sin interpolaciones -> comillas simples. (Se repite en varios sitios).

2017-05-02 14:16 UTC, ace commented on app/views/custom/admin/verifications/index.html.erb
> +          admin_verifications_path({ user_id: user.id }.merge request.query_parameters),
Si sabemos que queremos mantener determinados parámetros de la llamada anterior (asumo que `:term` y `:page`) pongamos un slice para quedarnos con esos dos y solo esos dos. Tal y como está el merge, nos pueden meter la basura que sea en la url y la iremos arrastrando.

2017-05-02 14:16 UTC, ace commented on config/routes.rb
> +      delete :destroy, on: :collection
Una de las dos rutas sobra, no hay dos destroys. Lo amplio en un comentario genérico sobre la solución en general.

2017-05-03 07:50 UTC, ace commented on app/controllers/custom/admin/verifications_controller.rb
> +    @user.destroy_verification(@user)
Si invocas el método sobre una instancia no necesitas pasarle ese mismo objeto como parámetro.

2017-05-03 07:50 UTC, ace commented on app/models/custom/user.rb
> +  def destroy_verification(user)
El método se va a ejecutar en el contexto de una instancia, pasarle otra como parámetro (salvo que hagas cosas con dos instancias distintas) sobra. En la línea de abajo en lugar de llamar al update del objeto parámetro, se llama al de la instancia en la que estamos (quita el `user.`).

2017-05-03 09:08 UTC, shernade commented on app/models/custom/user.rb
> +    update_attributes(document_number: nil, residence_verified_at: nil)
entiendo que no hay nada del modelo que validar con esta acción, ¿no?

2017-05-03 17:07 UTC, eLafo requested changes
Los ficheros de traducción deberían ir ordenados alfabéticamente.

Ya sé que muchos vendrán ya así, pero a medida que vayamos editando dichos ficheros podríamos ir arreglándolos.

2017-05-03 17:07 UTC, eLafo commented on config/locales/custom/admin.en.yml
> +      cancel_verification: Cancel verification
Los ficheros de traducción tienes que ir ordenados por orden alfabético

2017-05-03 17:07 UTC, eLafo commented on config/locales/custom/admin.es.yml
> +      cancel_verification: Cancelar verificación
Los ficheros de traducción tienes que ir ordenados por orden alfabético

2017-05-10 08:31 UTC, eLafo commented on config/routes.rb
> +      delete :destroy, on: :collection
por qué esta acción actúa a nivel de collection y no de member?

2017-05-10 08:40 UTC, ace commented on config/routes.rb
> +      delete :destroy, on: :collection
Leete mi tocho de arriba ;)

2017-05-11 10:28 UTC, ace approved these changes
Por mi ok. Squash, rebase y 🚢

2017-05-11 11:46 UTC, eLafo approved these changes

2017-05-11 11:47 UTC, merged